[package]
name = "peekd-ebpf"
version = "0.1.1"
edition = "2021"

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
peekd-common = { path = "../peekd-common", default-features = false }

[[bin]]
name = "peekd-ebpf"
path = "src/main.rs"
