//! xtask: Build tooling for peekd workspace.
//!
//! The libbpf eBPF object is generated by `peekd/build.rs` during the normal
//! userspace build. This helper keeps the historical `build-ebpf` command as a
//! validation alias for release scripts and operators.

use std::path::PathBuf;
use std::process::Command;

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();

    match args.first().map(|s| s.as_str()) {
        Some("build-ebpf") => build_ebpf(args.contains(&"--release".to_string()))?,
        Some(cmd) => anyhow::bail!("unknown command: {}", cmd),
        None => {
            eprintln!("Usage: cargo xtask build-ebpf [--release]");
            std::process::exit(1);
        }
    }

    Ok(())
}

fn build_ebpf(release: bool) -> anyhow::Result<()> {
    let workspace_root = workspace_root()?;
    let mut cmd = Command::new("cargo");
    cmd.current_dir(&workspace_root);
    cmd.arg("build");
    if release {
        cmd.arg("--release");
    }
    cmd.args(["-p", "peekd"]);

    eprintln!("[xtask] building peekd to generate libbpf eBPF object");
    let status = cmd.status()?;
    if !status.success() {
        anyhow::bail!("peekd build failed while generating libbpf eBPF object");
    }

    let obj = workspace_root
        .join("target")
        .join("bpf")
        .join("peekd.bpf.o");
    let metadata = std::fs::metadata(&obj)
        .map_err(|err| anyhow::anyhow!("missing libbpf object {}: {err}", obj.display()))?;
    if metadata.len() == 0 {
        anyhow::bail!("empty libbpf object: {}", obj.display());
    }
    eprintln!(
        "[xtask] BPF object: {} ({}B)",
        obj.display(),
        metadata.len()
    );
    Ok(())
}

fn workspace_root() -> anyhow::Result<PathBuf> {
    let output = Command::new("cargo")
        .args(["locate-project", "--workspace", "--message-format=plain"])
        .output()?;
    let path = String::from_utf8(output.stdout)?;
    Ok(PathBuf::from(path.trim()).parent().unwrap().to_path_buf())
}
